{
 "title": "Trivy Operator - Overview",
 "description": "This Dashboard is used to provide an overview of the metrics from the security reports of the Trivy Operator",
 "tags": [
  "trivy",
  "trivy operator",
  "security",
  "security scanning",
  "vulnerabilities",
  "exposed secrets",
  "misconfiguration",
  "managed-by: terraform"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  { "title": "Quick Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number and Type of Security Issues",
   "type": "stat",
   "description": "Total number by type of security issues identified in the cluster",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(trivy_image_vulnerabilities{cluster=\"$cluster\"})",
     "legendFormat": "Vulnerabilities"
    },
    {
     "expr": "sum(trivy_resource_configaudits{cluster=\"$cluster\"})",
     "legendFormat": "Misconfiguration"
    },
    {
     "expr": "sum(trivy_image_exposedsecrets{cluster=\"$cluster\"})",
     "legendFormat": "Exposed Secrets"
    },
    {
     "expr": "sum(trivy_clusterrole_clusterrbacassessments{cluster=\"$cluster\"})",
     "legendFormat": "RBAC Assessment"
    }
   ]
  },
  { "title": "Vulnerabilities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Severity Breakdown of all Vulnerabilities",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(trivy_image_vulnerabilities{cluster=\"$cluster\", severity=\"Critical\"})",
     "legendFormat": "Critical"
    },
    {
     "expr": "sum(trivy_image_vulnerabilities{cluster=\"$cluster\", severity=\"High\"})",
     "legendFormat": "High"
    },
    {
     "expr": "sum(trivy_image_vulnerabilities{cluster=\"$cluster\", severity=\"Medium\"})",
     "legendFormat": "Medium"
    },
    {
     "expr": "sum(trivy_image_vulnerabilities{cluster=\"$cluster\", severity=\"Low\"})",
     "legendFormat": "Low"
    },
    {
     "expr": "sum(trivy_image_vulnerabilities{cluster=\"$cluster\", severity=\"Unknown\"})",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "Number of Vulnerabilities by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(trivy_image_vulnerabilities{cluster=\"$cluster\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vulnerability by Image",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(trivy_image_vulnerabilities{cluster=\"$cluster\", severity=\"Critical\"}) by (image_repository,image_tag)"
    },
    {
     "expr": "sum(trivy_image_vulnerabilities{cluster=\"$cluster\", severity=\"High\"}) by (image_repository,image_tag)"
    },
    {
     "expr": "sum(trivy_image_vulnerabilities{cluster=\"$cluster\", severity=\"Medium\"}) by (image_repository,image_tag)"
    },
    {
     "expr": "sum(trivy_image_vulnerabilities{cluster=\"$cluster\", severity=\"Low\"}) by (image_repository,image_tag)"
    },
    {
     "expr": "sum(trivy_image_vulnerabilities{cluster=\"$cluster\", severity=\"Unknown\"}) by (image_repository,image_tag)"
    }
   ]
  },
  { "title": "Misconfiguration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Severity Breakdown of all Misconfiguration",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(trivy_resource_configaudits{cluster=\"$cluster\", severity=\"Critical\"}) ",
     "legendFormat": "Critical"
    },
    {
     "expr": "sum(trivy_resource_configaudits{cluster=\"$cluster\", severity=\"High\"})",
     "legendFormat": "High"
    },
    {
     "expr": "sum(trivy_resource_configaudits{cluster=\"$cluster\", severity=\"Medium\"})",
     "legendFormat": "Medium"
    },
    {
     "expr": "sum(trivy_resource_configaudits{cluster=\"$cluster\", severity=\"Low\"})",
     "legendFormat": "Low"
    }
   ]
  },
  { "title": "RBAC Assessment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Severity Breakdown of RBAC Security Issues",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(trivy_role_rbacassessments{cluster=\"$cluster\", severity=\"Critical\"})",
     "legendFormat": "Critical"
    },
    {
     "expr": "sum(trivy_role_rbacassessments{cluster=\"$cluster\", severity=\"High\"})",
     "legendFormat": "High"
    },
    {
     "expr": "sum(trivy_role_rbacassessments{cluster=\"$cluster\", severity=\"Medium\"})",
     "legendFormat": "Medium"
    },
    {
     "expr": "sum(trivy_role_rbacassessments{cluster=\"$cluster\", severity=\"Low\"})",
     "legendFormat": "Low"
    },
    {
     "expr": "sum(trivy_role_rbacassessments{cluster=\"$cluster\", severity=\"UNKNOWN\"})",
     "legendFormat": "Unknown"
    }
   ]
  },
  { "title": "Exposed Secrets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Exposed Secrets per namespace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "sum(trivy_image_exposedsecrets{cluster=\"$cluster\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}