provider:
    GRAFANA_AUTH: ENC[AES256_GCM,data:A5oes8QB4fm2PIWHJe7alQ==,iv:KyCtL+Ex27+1jRoMx4kk5XKXPO9O1xUX5LjBb1SSNQM=,tag:IZzCW9YKLwRM1kKIVH3KYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-08-25T12:39:39Z"
    mac: ENC[AES256_GCM,data:D5jNb/AsKIJlBn3IBq2MCDaUcnp94BtFek5PZc32X13F7CTg+JyIc0IMNBcjrjEAyzGs5FOKaBTC6mGsLGmUhNP9L29f1VZ2cGZYX5z9ox9uKnv5t93r/hFxSCON3FggQXgv6YY72QvXN+Ohguc8rVIu3qqVFmIy9HqL7eY8mHY=,iv:cxec76qyt7eH/n22TcpneG6dDlEsNuAyIjKafDkhJAQ=,tag:JTKyUNdWxQqESHBUqGm62Q==,type:str]
    pgp:
        - created_at: "2024-08-25T12:38:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/9TFoYm/JQlARAAkHMk/CHTg3iPfAsSMdT3UiFaeZdXDK3gcnfVu2giS/ZG
            SKYigB9BvHBvPTEdh2LyXx8lhQQqu828XkB0il8hwIOh5oc79Rf/KGqnb/fnEzK3
            rWl6LTdMU0RQ3mwFmmHDzSQ04h6KI5kN0yGhXVl27qOsloPAmerGi2B5loPDjSOg
            2IDYOqieaDdOMzORp0xpqqVdTcIgJSksQZmjXtRrFbB+wAkCKG1Rd4Kn02IwPChf
            Ugz+FqnHQWycxMHfBPb+IxiRWU2AG6UG6O72Iz33oMZvM1OFLnL64errm1t//LnP
            gk2vCmxBMPguhO1+hJ3RTStHj5vgtlp1uFYuZqhlfXsI9/XgaUkzww40vP+cM/6y
            MidoDXjxNwMWSoY78+goYBYk2XLKdlr1GrYhmr503kvVWBqGUv8yIEsLzj61HdHW
            wzYb9koLRGXXUScpROydMHArJtkU0MXS0i/L7pDHHOFDatna2Lb7ut9yKGSX+6JD
            qYAUIB9+bIt6bugBuhOSM5Ngsu9B1Weree5/zgnJQhLWUokcmZoZzKd9l4DkY5iz
            VMRGh3UB8b7vXPHAEo3lKQuEf4VCrRYjOzArfMocOGsUu5hf8PVmgAGmvGqFpy1Y
            3qYGau/eiAzyarlaSZoRHvoSNd7AMG37kOVHdwTaY7/dU7bkVQ1w/qju/C0Jd+fS
            XgGgoe+5BZmMa6sa4VgGlbYlD+Mg+EVDYeJdGrVWDS9YlQfRnEUMCnPLZWoi7mP6
            1nEAnZ46WPo3oh32ytZn6LtlbSC0nIi2dzxNQEz/2C5qpBpki4NC5dI5iSdy3e8=
            =FY0F
            -----END PGP MESSAGE-----
          fp: 341D131BB60927AAF88754DB382FFDD21F03A21C
    unencrypted_suffix: _unencrypted
    version: 3.8.1
