{
 "title": "Kubernetes / System / Cluster Autoscaler",
 "description": "Super simple dashboard showing an overview of kubernetes cluster autoscaling activity and status, using metrics reported by the autoscaler to prometheus.\r\n\r\nhttps://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler",
 "tags": [
  "Kubernetes",
  "Prometheus",
  "Cluster Autoscaler",
  "managed-by: terraform"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "Total nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_nodes_count{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes available",
   "type": "gauge",
   "description": "Shows the nodes which are ready as a percent of the total nodes",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_nodes_count{cluster=\"$cluster\", state=\"ready\"})/sum(cluster_autoscaler_nodes_count{cluster=\"$cluster\"})*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Is cluster safe to scale?",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_cluster_safe_to_autoscale{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of unscheduled pods",
   "type": "stat",
   "description": "Tells you if there are unscheduled pods",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_unschedulable_pods_count{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last scaleDown activity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time()-cluster_autoscaler_last_activity{cluster=\"$cluster\", activity=\"scaleDown\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last autoscale activity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time()-cluster_autoscaler_last_activity{cluster=\"$cluster\", activity=\"autoscaling\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod activity",
   "type": "timeseries",
   "description": "Shows the evicted and unscheduled pods",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_evicted_pods_total{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(cluster_autoscaler_unschedulable_pods_count{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node activity",
   "type": "timeseries",
   "description": "Shows the state of the nodes as scaling happens",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_nodes_count{cluster=\"$cluster\", state=\"ready\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(cluster_autoscaler_nodes_count{cluster=\"$cluster\", state=\"unready\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(cluster_autoscaler_nodes_count{cluster=\"$cluster\", state=\"notStarted\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Autoscaling activity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_scaled_up_nodes_total{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(cluster_autoscaler_unneeded_nodes_count{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(cluster_autoscaler_nodes_count{cluster=\"$cluster\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster direction?",
   "type": "stat",
   "description": "Is the cluster scaling up, down or ticking along okay?",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_scaled_up_nodes_total{cluster=\"$cluster\"})-sum(cluster_autoscaler_scaled_down_nodes_total{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}