{
 "title": "Kubernetes / System / CoreDNS",
 "description": "This is a modern CoreDNS dashboard for your Kubernetes cluster(s). Made for kube-prometheus-stack and take advantage of the latest Grafana features. GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "tags": [
  "Kubernetes",
  "Prometheus",
  "CoreDNS",
  "managed-by: terraform"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{cluster=\"$cluster\", job=\"coredns\"},instance)"
    }
   },
   {
    "name": "protocol",
    "query": {
     "query": "label_values(coredns_dns_requests_total{cluster=\"$cluster\"},proto)"
    }
   },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" }
  ]
 },
 "panels": [
  { "title": "CoreDNS - Global stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests (by instance)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{cluster=\"$cluster\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "CoreDNS - Health: $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "instance" },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "coredns_build_info{instance=~\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{cluster=\"$cluster\", job=\"coredns\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstream Health Check Fails",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(coredns_forward_healthcheck_broken_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Upstream Rejected Queries",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(coredns_forward_max_concurrent_rejects_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Panics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(coredns_panics_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed Reloads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(coredns_reload_failed_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{cluster=\"$cluster\"} * on(namespace, pod) group_left(instance) up{cluster=\"$cluster\", job=\"coredns\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Local", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CoreDNS - CPU Usage by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", image!=\"\"}[$__rate_interval]) * on (namespace, pod) group_left(instance) up{cluster=\"$cluster\", job=\"coredns\", instance=~\"$instance\"} ",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CoreDNS - Memory Usage by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{cluster=\"$cluster\"} * on(namespace, pod) group_left(instance) up{cluster=\"$cluster\", job=\"coredns\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CoreDNS - Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{instance=~\"$instance\"}[5m])) by (server)",
     "legendFormat": "{{server}}"
    },
    {
     "expr": "sum(rate(coredns_cache_requests_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "cache"
    }
   ]
  },
  {
   "title": "CoreDNS - Requests by type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{cluster=\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "CoreDNS - Requests by return code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_responses_total{cluster=\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (rcode)",
     "legendFormat": "{{ rcode }}"
    }
   ]
  },
  {
   "title": "CoreDNS - Average Packet Size  ($protocol)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_size_bytes_sum{cluster=\"$cluster\", instance=~\"$instance\",proto=\"$protocol\"}[$__rate_interval])) by (proto) / sum(rate(coredns_dns_request_size_bytes_count{cluster=\"$cluster\", instance=~\"$instance\",proto=\"$protocol\"}[$__rate_interval])) by (proto)",
     "legendFormat": "average $protocol packet size"
    }
   ]
  },
  {
   "title": "CoreDNS - Cache Hits / Misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{cluster=\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{ type }}"
    },
    {
     "expr": "sum(rate(coredns_cache_misses_total{cluster=\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (type)",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "CoreDNS - Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{instance=~\"$instance\", type=\"success\"}[5m])) / sum(rate(coredns_cache_requests_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "hits: success"
    },
    {
     "expr": "sum(rate(coredns_cache_hits_total{instance=~\"$instance\", type=\"denial\"}[5m])) / sum(rate(coredns_cache_requests_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "hits: denial"
    },
    {
     "expr": "(sum(rate(coredns_cache_requests_total{instance=~\"$instance\"}[5m])) - sum(rate(coredns_cache_hits_total{instance=~\"$instance\", type=\"success\"}[5m]))) / sum(rate(coredns_cache_requests_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "misses"
    },
    {
     "expr": "sum(rate(coredns_dnssec_cache_hits_total{instance=~\"$instance\"}[5m])) / sum(rate(coredns_cache_requests_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "hits: DNSSEC"
    },
    {
     "expr": "(sum(rate(coredns_cache_requests_total{instance=~\"$instance\"}[5m])) - sum(rate(coredns_dnssec_cache_hits_total{instance=~\"$instance\"}[5m]))) / sum(rate(coredns_cache_requests_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "misses: DNSSEC"
    }
   ]
  },
  {
   "title": "CoreDNS - Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(coredns_cache_entries{cluster=\"$cluster\"}) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "CoreDNS - DNS Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_forward_responses_total{cluster=\"$cluster\", rcode=~\"SERVFAIL|REFUSED\"}[$__rate_interval])) by (rcode)",
     "legendFormat": "{{ rcode }}"
    }
   ]
  },
  {
   "title": "CoreDNS - Responses Latency (Internet Zone)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_duration_seconds_bucket{instance=~\"$instance\", zone=\".\"}[5m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_request_duration_seconds_bucket{instance=~\"$instance\", zone=\".\"}[5m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_duration_seconds_bucket{instance=~\"$instance\", zone=\".\"}[5m])) by (le))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "CoreDNS - DNS request duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "sum(increase(coredns_dns_request_duration_seconds_bucket{cluster=\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "CoreDNS - DNS request size",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "sum(increase(coredns_dns_request_size_bytes_bucket{cluster=\"$cluster\", instance=~\"$instance\", le!=\"0\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "CoreDNS - DNS response size",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "sum(increase(coredns_dns_response_size_bytes_bucket{cluster=\"$cluster\", instance=~\"$instance\", le!=\"0\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "CoreDNS - Responses (by code)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_responses_total{instance=~\"$instance\"}[5m])) by (rcode)",
     "legendFormat": "{{rcode}}"
    }
   ]
  },
  {
   "title": "Core DNS - Requests Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_size_bytes_bucket{instance=~\"$instance\", zone=\".\"}[5m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_request_size_bytes_bucket{instance=~\"$instance\", zone=\".\"}[5m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_size_bytes_bucket{instance=~\"$instance\", zone=\".\"}[5m])) by (le))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "CoreDNS - Responses Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_response_size_bytes_bucket{instance=~\"$instance\", zone=\".\"}[5m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_response_size_bytes_bucket{instance=~\"$instance\", zone=\".\"}[5m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_response_size_bytes_bucket{instance=~\"$instance\", zone=\".\"}[5m])) by (le))",
     "legendFormat": "50%"
    }
   ]
  },
  { "title": "Forward", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "CoreDNS - Total Forward Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_forward_requests_total{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "total forward requests"
    }
   ]
  },
  {
   "title": "CoreDNS - Forward Requests (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_forward_requests_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "upstream"
    }
   ]
  },
  {
   "title": "CoreDNS - Forward Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_forward_conn_cache_hits_total{instance=~\"$instance\"}[5m])) / sum(rate(coredns_forward_requests_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "hits"
    },
    {
     "expr": "(sum(rate(coredns_forward_requests_total{instance=~\"$instance\"}[5m])) - sum(rate(coredns_forward_conn_cache_hits_total{instance=~\"$instance\"}[5m]))) / sum(rate(coredns_forward_requests_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "CoreDNS - Forward Responses Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_forward_request_duration_seconds_bucket{instance=~\"$instance\"}[5m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_forward_request_duration_seconds_bucket{instance=~\"$instance\"}[5m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_forward_request_duration_seconds_bucket{instance=~\"$instance\"}[5m])) by (le))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "CoreDNS - Forward request duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "targets": [
    {
     "expr": "sum(increase(coredns_forward_request_duration_seconds_bucket{cluster=\"$cluster\", instance=~\"$instance\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "CoreDNS - Forward Requests (by upstream)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(coredns_forward_requests_total{instance=~\"$instance\"}[5m])) by (to)",
     "legendFormat": "{{rcode}}"
    }
   ]
  },
  {
   "title": "CoreDNS - Forward Responses (by code)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(coredns_forward_responses_total{instance=~\"$instance\"}[5m])) by (rcode)",
     "legendFormat": "{{rcode}}"
    }
   ]
  }
 ]
}