{
 "title": "ArgoCD / Application / Overview",
 "description": "A dashboard that monitors ArgoCD with a focus on Application status. It is created using the [argo-cd-mixin](https://github.com/adinhodovic/argo-cd-mixin). Requires custom configuration to add application badges. Please refer to the mixin.",
 "tags": [
  "argocd",
  "managed-by: terraform"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(argocd_app_info{cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(argocd_app_info{namespace=~\"$namespace\", cluster=\"$cluster\"},job)"
    }
   },
   {
    "name": "argocd_cluster",
    "label": "ArgoCD Cluster",
    "query": {
     "query": "label_values(argocd_app_info{namespace=~\"$namespace\", job=~\"$job\", cluster=\"$cluster\"},dest_server)"
    }
   },
   {
    "name": "project",
    "label": "Project",
    "query": {
     "query": "label_values(argocd_app_info{namespace=~\"$namespace\", job=~\"$job\", dest_server=~\"$argocd_cluster\", cluster=\"$cluster\"},project)"
    }
   },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(argocd_app_info{namespace=~\"$namespace\", job=~\"$job\", dest_server=~\"$argocd_cluster\", project=~\"$project\", cluster=\"$cluster\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary by Cluster, Project", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Application Health Status",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{cluster='$cluster',\n    namespace=~'$namespace',\njob=~'$job',\ndest_server=~'$argocd_cluster',\nproject=~'$project',\n\n  }\n) by (job, dest_server, project, health_status)\n",
     "legendFormat": "{{ dest_server }}/{{ project }} - {{ health_status }}"
    }
   ]
  },
  {
   "title": "Application Sync Status",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{cluster='$cluster',\n    namespace=~'$namespace',\njob=~'$job',\ndest_server=~'$argocd_cluster',\nproject=~'$project',\n\n  }\n) by (job, dest_server, project, sync_status)\n",
     "legendFormat": "{{ dest_server }}/{{ project }} - {{ sync_status }}"
    }
   ]
  },
  { "title": "Application Badges", "type": "text", "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 }, "options": { "content": "No applications defined" } },
  {
   "title": "Application Syncs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  round(\n    increase(\n      argocd_app_sync_total{cluster='$cluster',\n        namespace=~'$namespace',\njob=~'$job',\ndest_server=~'$argocd_cluster',\nproject=~'$project',\n\n      }[$__rate_interval]\n    )\n  )\n) by (job, dest_server, project, phase)\n",
     "legendFormat": "{{ dest_server }}/{{ project }} - {{ phase }}"
    }
   ]
  },
  {
   "title": "Application Auto Sync Enabled",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{cluster='$cluster',\n    namespace=~'$namespace',\njob=~'$job',\ndest_server=~'$argocd_cluster',\nproject=~'$project',\n\n  }\n) by (job, dest_server, project, autosync_enabled)\n",
     "legendFormat": "{{ dest_server }}/{{ project }} - {{ autosync_enabled }}"
    }
   ]
  },
  {
   "title": "Applications (Unhealthy/OutOfSync/AutoSyncDisabled) Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "Applications Unhealthy",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{cluster='$cluster',\n    namespace=~'$namespace',\njob=~'$job',\ndest_server=~'$argocd_cluster',\nproject=~'$project',\n\n    health_status!~\"Healthy|Progressing\"\n  }\n) by (job, dest_server, project, name, health_status)\n"
    }
   ]
  },
  {
   "title": "Applications Out Of Sync",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{cluster='$cluster',\n    namespace=~'$namespace',\njob=~'$job',\ndest_server=~'$argocd_cluster',\nproject=~'$project',\n\n    sync_status!=\"Synced\"\n  }\n) by (job, dest_server, project, name, sync_status) > 0\n"
    }
   ]
  },
  {
   "title": "Applications That Failed to Sync[7d]",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  round(\n    increase(\n      argocd_app_sync_total{cluster='$cluster',\n        namespace=~'$namespace',\njob=~'$job',\ndest_server=~'$argocd_cluster',\nproject=~'$project',\n\n        phase!=\"Succeeded\"\n      }[7d]\n    )\n  )\n) by (job, dest_server, project, name, phase) > 0\n"
    }
   ]
  },
  {
   "title": "Applications With Auto Sync Disabled",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{cluster='$cluster',\n    namespace=~'$namespace',\njob=~'$job',\ndest_server=~'$argocd_cluster',\nproject=~'$project',\n\n    autosync_enabled!=\"true\"\n  }\n) by (job, dest_server, project, name, autosync_enabled) > 0\n"
    }
   ]
  },
  {
   "title": "Application ($application)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Application Health Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\n  argocd_app_info{cluster='$cluster',\n    namespace=~'$namespace',\njob=~'$job',\ndest_server=~'$argocd_cluster',\nproject=~'$project',\n\n    name=~\"$application\",\n  }\n) by (namespace, job, dest_server, project, name, health_status)\n",
       "legendFormat": "{{ dest_server }}/{{ project }}/{{ name }} - {{ health_status }}"
      }
     ]
    },
    {
     "title": "Application Sync Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\n  argocd_app_info{cluster='$cluster',\n    namespace=~'$namespace',\njob=~'$job',\ndest_server=~'$argocd_cluster',\nproject=~'$project',\n\n    name=~\"$application\",\n  }\n) by (namespace, job, dest_server, project, name, sync_status)\n",
       "legendFormat": "{{ dest_server }}/{{ project }}/{{ name }} - {{ sync_status }}"
      }
     ]
    },
    {
     "title": "Application Sync Result",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(\n  round(\n    increase(\n      argocd_app_sync_total{cluster='$cluster',\n        namespace=~'$namespace',\njob=~'$job',\ndest_server=~'$argocd_cluster',\nproject=~'$project',\n\n        name=~\"$application\",\n      }[$__rate_interval]\n    )\n  )\n) by (namespace, job, dest_server, project, name, phase)\n",
       "legendFormat": "{{ dest_server }}/{{ project }}/{{ name }} - {{ phase }}"
      }
     ]
    }
   ]
  }
 ]
}