{
 "title": "ArgoCD Overview",
 "tags": [
  "argocd",
  "managed-by: terraform"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\"},namespace)"
    }
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h,2h,4h,8h" },
   { "name": "grouping", "query": "namespace,name,project" },
   {
    "name": "argo_cluster",
    "query": {
     "query": "label_values(argocd_cluster_info{cluster=\"$cluster\"},server)"
    }
   },
   {
    "name": "health_status",
    "query": "Healthy,Progressing,Suspended,Missing,Degraded,Unknown"
   },
   { "name": "sync_status", "query": "Synced,OutOfSync,Unknown" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": {
    "content": "![argoimage](https://avatars1.githubusercontent.com/u/30269780?s=110&v=4)"
   }
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{cluster=\"$cluster\",job=\"argo-cd-server-metrics\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Clusters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (server) (argocd_cluster_info{cluster=\"$cluster\",namespace=~\"$namespace\"}))"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{cluster=\"$cluster\",namespace=~\"$namespace\",dest_server=~\"$argo_cluster\",health_status=~\"$health_status\",sync_status=~\"$sync_status\"})"
    }
   ]
  },
  {
   "title": "Repositories",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (repo) (argocd_app_info{cluster=\"$cluster\",namespace=~\"$namespace\"}))"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{cluster=\"$cluster\",namespace=~\"$namespace\",dest_server=~\"$argo_cluster\",operation!=\"\"})"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{cluster=\"$cluster\",namespace=~\"$namespace\",dest_server=~\"$argo_cluster\",health_status=~\"$health_status\",sync_status=~\"$sync_status\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Application Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Health Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{cluster=\"$cluster\",namespace=~\"$namespace\",dest_server=~\"$argo_cluster\",health_status=~\"$health_status\",sync_status=~\"$sync_status\",health_status!=\"\"}) by (health_status)",
     "legendFormat": "{{health_status}}"
    }
   ]
  },
  {
   "title": "Sync Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(argocd_app_info{cluster=\"$cluster\",namespace=~\"$namespace\",dest_server=~\"$argo_cluster\",health_status=~\"$health_status\",sync_status=~\"$sync_status\",health_status!=\"\"}) by (sync_status)",
     "legendFormat": "{{sync_status}}"
    }
   ]
  },
  { "title": "Sync Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Sync Activity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(round(increase(argocd_app_sync_total{cluster=\"$cluster\", namespace=~\"$namespace\",dest_server=~\"$argo_cluster\"}[$interval]))) by ($grouping)",
     "legendFormat": "{{$grouping}}"
    }
   ]
  },
  {
   "title": "Sync Failures",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(round(increase(argocd_app_sync_total{cluster=\"$cluster\",namespace=~\"$namespace\",phase=~\"Error|Failed\",dest_server=~\"$argo_cluster\"}[$interval]))) by ($grouping, phase)",
     "legendFormat": "{{phase}}: {{$grouping}}"
    }
   ]
  },
  { "title": "Controller Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Reconciliation Activity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(increase(argocd_app_reconcile_count{cluster=\"$cluster\",namespace=~\"$namespace\",dest_server=~\"$argo_cluster\"}[$interval])) by ($grouping)",
     "legendFormat": "{{$grouping}}"
    }
   ]
  },
  {
   "title": "Reconciliation Performance",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(increase(argocd_app_reconcile_bucket{cluster=\"$cluster\",namespace=~\"$namespace\"}[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "K8s API Activity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(increase(argocd_app_k8s_request_total{cluster=\"$cluster\",namespace=~\"$namespace\",server=~\"$argo_cluster\"}[$interval])) by (verb, resource_kind)",
     "legendFormat": "{{verb}} {{resource_kind}}"
    }
   ]
  },
  {
   "title": "Workqueue Depth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum(workqueue_depth{cluster=\"$cluster\",namespace=~\"$namespace\",name=~\"app_.*\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pending kubectl run",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "sum(argocd_kubectl_exec_pending{cluster=\"$cluster\",namespace=~\"$namespace\"}) by (command)",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Controller Telemetry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 436 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{cluster=\"$cluster\",job=\"argo-cd-metrics\",namespace=~\"$namespace\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 596 },
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{cluster=\"$cluster\",job=\"argo-cd-metrics\",namespace=~\"$namespace\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 603 },
     "targets": [
      {
       "expr": "go_goroutines{cluster=\"$cluster\",job=\"argo-cd-metrics\",namespace=~\"$namespace\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Resource Objects Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 437 },
     "targets": [
      {
       "expr": "sum(argocd_cluster_api_resource_objects{cluster=\"$cluster\",namespace=~\"$namespace\",server=~\"$argo_cluster\"}) by (server)",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "API Resources Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 577 },
     "targets": [
      {
       "expr": "  sum(argocd_cluster_api_resources{cluster=\"$cluster\",namespace=~\"$namespace\",server=~\"$argo_cluster\"}) by (server)",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Cluster Events Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 583 },
     "targets": [
      {
       "expr": "sum(increase(argocd_cluster_events_total{cluster=\"$cluster\",namespace=~\"$namespace\",server=~\"$argo_cluster\"}[$interval])) by (server)",
       "legendFormat": "{{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Repo Server Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Git Requests (ls-remote)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 438 },
     "targets": [
      {
       "expr": "sum(increase(argocd_git_request_total{cluster=\"$cluster\",request_type=\"ls-remote\", namespace=~\"$namespace\"}[10m])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Git Requests (checkout)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 438 },
     "targets": [
      {
       "expr": "sum(increase(argocd_git_request_total{cluster=\"$cluster\",request_type=\"fetch\", namespace=~\"$namespace\"}[10m])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Git Fetch Performance",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 517 },
     "targets": [
      {
       "expr": "sum(increase(argocd_git_request_duration_seconds_bucket{cluster=\"$cluster\",request_type=\"fetch\", namespace=~\"$namespace\"}[$interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Git Ls-Remote Performance",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 517 },
     "targets": [
      {
       "expr": "sum(increase(argocd_git_request_duration_seconds_bucket{cluster=\"$cluster\",request_type=\"ls-remote\", namespace=~\"$namespace\"}[$interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 525 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{cluster=\"$cluster\",job=\"argo-cd-repo-server-metrics\",namespace=~\"$namespace\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 533 },
     "targets": [
      {
       "expr": "go_goroutines{cluster=\"$cluster\",job=\"argo-cd-repo-server-metrics\",namespace=~\"$namespace\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  { "title": "Server Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{cluster=\"$cluster\",job=\"argo-cd-server-metrics\",namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "go_goroutines{cluster=\"$cluster\",job=\"argo-cd-server-metrics\",namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC Time Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{cluster=\"$cluster\",job=\"argo-cd-server-metrics\", quantile=\"1\", namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 81 },
   "options": {
    "content": "# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)"
   }
  },
  {
   "title": "ApplicationService Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{cluster=\"$cluster\",job=\"argo-cd-server-metrics\",grpc_service=\"application.ApplicationService\",namespace=~\"$namespace\"}[$interval])) by (grpc_code, grpc_method)",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "ClusterService Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 83 },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{cluster=\"$cluster\",job=\"argo-cd-server-metrics\",grpc_service=\"cluster.ClusterService\",namespace=~\"$namespace\"}[$interval])) by (grpc_code, grpc_method)",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "ProjectService Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{cluster=\"$cluster\",job=\"argo-cd-server-metrics\",grpc_service=\"project.ProjectService\",namespace=~\"$namespace\"}[$interval])) by (grpc_code, grpc_method)",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "RepositoryService Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 92 },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{cluster=\"$cluster\",job=\"argo-cd-server-metrics\",grpc_service=\"repository.RepositoryService\",namespace=~\"$namespace\"}[$interval])) by (grpc_code, grpc_method)",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "SessionService Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 101 },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{cluster=\"$cluster\",job=\"argo-cd-server-metrics\",grpc_service=\"session.SessionService\",namespace=~\"$namespace\"}[$interval])) by (grpc_code, grpc_method)",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "VersionService Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 101 },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{cluster=\"$cluster\",job=\"argo-cd-server-metrics\",grpc_service=\"version.VersionService\",namespace=~\"$namespace\"}[$interval])) by (grpc_code, grpc_method)",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "AccountService Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 110 },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{cluster=\"$cluster\",job=\"argo-cd-server-metrics\",grpc_service=\"account.AccountService\",namespace=~\"$namespace\"}[$interval])) by (grpc_code, grpc_method)",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  {
   "title": "SettingsService Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 110 },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{cluster=\"$cluster\",job=\"argo-cd-server-metrics\",grpc_service=\"settings.SettingsService\",namespace=~\"$namespace\"}[$interval])) by (grpc_code, grpc_method)",
     "legendFormat": "{{grpc_code}},{{grpc_method}}"
    }
   ]
  },
  { "title": "Redis Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 } },
  {
   "title": "Requests by result",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 120 },
   "targets": [
    {
     "expr": "sum(increase(argocd_redis_request_total{cluster=\"$cluster\",namespace=~\"$namespace\"}[$interval])) by (failed)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}